### ISSUE TITLE
Setting "Block backend shutdown" not working

### ISSUE THREAD

**Issue by Miwer** [janbar/pvr.mythtv#116] opened 2019-03-25 20:54 UTC
Hi,

I'm wondering if the setting "Block backend shutdown" is working as intended for anyone?
It is not working for me, and it is something that has always annoyed me over several versions of the MythTV plugin.

For example, if I start my kodi, it will WOL my backend, and I can usually start watching TV within seconds. 

If I then stop watching TV, and go watch something from other addons, then my backend would usually go to sleep within 15 minutes (as it's setup to do, but only when no clients are connected). This is where I'd think that the setting "Block backend shutdown" would prevent this.

Instead, when I'm done watching other stuff, and want to watch TV again, the backend is sleeping, and the plugin fails to start TV with the "channel unavailable" message. I can then switch between channels (being "unavailable"), and stop/start Live TV a couple of times, before the plugin sends another WOL to wake the backend, before I can successfully start LiveTV.

Any thoughts on this?

**Comment by janbar** [comment] 2019-03-28 20:41
What is the backend version and the Kodi version ?

When you enable the setting "Block backend shutdown", the plugin open the control connection with the backend and send the command "BLOCK_SHUTDOWN". The plugin send "ALLOW_SHUTDOWN" when kodi want to sleep after a period of inactivity, and the plugin should send again "BLOCK_SHUTDOWN" after the connection is restored. Also any disconnection (caused by network issue) will allow the backend to shutdown.

**Comment by Miwer** [comment] 2019-03-29 16:24
~$ mythbackend --version
Please attach all output as a file in bug reports.
MythTV Version : v29.1
MythTV Branch : 
Network Protocol : 91
Library API : 29.20180316-1
QT Version : 5.9.5
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_crystalhd using_dvb using_firewire using_frontend using_hdhomerun using_vbox using_ceton using_hdpvr using_ivtv using_joystick_menu using_libcec using_libcrypto using_libdns_sd using_libfftw3 using_libxml2 using_lirc using_mheg using_opengl using_opengl_video using_opengl_themepainter using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_x11 using_xrandr using_xv using_profiletype using_systemd_notify using_systemd_journal using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_vaapi using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame

Frontend version:
Starting Kodi (18.1 Git:18.1-Leia). Platform: Linux ARM 32-bit
Using Release Kodi x32 build
Kodi compiled 2019-02-27 by GCC 8.2.0 for Linux ARM 32-bit version 3.14.29 (200221)
Running on CoreELEC (official): 9.0.1, kernel: Linux ARM 64-bit version 3.14.29 aarch64
ADDON: pvr.mythtv v5.10.6.0 installed

Despite your description, I still don't understand what could be wrong. You say kodi want to sleep after a period of inactivity. In my case, Kodi is set to shutdown after 30 minutes of inactivity, but my issue is, that Kodi is not inactive, I'm using it to view/hear other things in other plugins, and still the backend goes to sleep despite the block backend shutdown being enabled. 

Do you mean to say, that the pvr plugin sends allow_shutdown to the backend after a period of not using the plugin (not Kodi in general)? Because then it would make sense what I'm seeing. 
I cannot rule out intermittent connection losses, since it is running on wireless, but generally I don't have trouble with network connectivity, that kodi or the plugin should not be able to recover from.

**Comment by janbar** [comment] 2019-03-29 17:07
The plugin send "allow_shutdown" only when kodi goes to sleep. So for your case the message isn't sended. It could be the setting of the backend doesn't take care of the blocking connection. You can enable the extra debug log of the plugin in the tab "Advanced settings" and enable the debug logging of kodi in the system setting, and selecting only the PVR component. Then you will see the message "block_shutdown" or "allow_shutdown" in the kodi log file as below.

In plugin settings / tab Advanced:
![Capture du 2019-03-29 17-56-22](https://user-images.githubusercontent.com/2353635/55249281-023c2900-524c-11e9-8128-2461f31a6c47.png)

In Kodi System settings / Logging / Specify component
![Capture du 2019-03-29 17-57-46](https://user-images.githubusercontent.com/2353635/55249364-2dbf1380-524c-11e9-9018-908523768492.png)

Finally enable debug logging:
![Capture du 2019-03-29 17-59-00](https://user-images.githubusercontent.com/2353635/55249454-60690c00-524c-11e9-9218-f13d09684531.png)


The log file should contains all plugin operations:
`DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: BLOCK_SHUTDOWN`

**Comment by Miwer** [comment] 2019-03-29 17:13
Thanks - I will try to do some more debug logging and testing, and see if I can detect a pattern, and report back.

**Comment by knappster1** [comment] 2019-04-06 20:25
Mine is working opposite of yours.  I have block shutdown disabled, but the remote backend never shuts down unless I exit kodi.  I just posted on kodi forums, but now that I see @janbar's detailed logging instructions I will try to produce a log.

**Comment by knappster1** [comment] 2019-04-07 12:27
My log is too big to post to pastebin.  If I launch it with the block shutdown setting disabled, I do not see any block_shutdown or allow_shutdown messages in the log.  If I enable it, I immediately get:

> 2019-04-06 18:44:02.360 T:1899470096    INFO: AddOnLog: MythTV PVR Client: Changed Setting 'block_shutdown' from 0 to 1
> 2019-04-06 18:44:02.360 T:1899470096   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: BLOCK_SHUTDOWN
> 2019-04-06 18:44:02.369 T:1899470096   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvMessageLength: 2
> 2019-04-06 18:44:02.369 T:1899470096   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)BlockShutdown75: succeeded

And after 3 minutes of inactivity when the screen saver kicks on:

> 2019-04-06 18:47:07.310 T:1899455216   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
> 2019-04-06 18:47:07.310 T:1899455216    INFO: AddOnLog: MythTV PVR Client: Received event: OnPowerSavingActivated
> 2019-04-06 18:47:07.311 T:1899455216   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: ALLOW_SHUTDOWN
> 2019-04-06 18:47:07.316 T:1899470096   DEBUG: CAddonSettings[screensaver.xbmc.builtin.dim]: loading setting definitions
> 2019-04-06 18:47:07.316 T:1899455216   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvMessageLength: 2
> 2019-04-06 18:47:07.316 T:1899470096   DEBUG: CAddonSettings[screensaver.xbmc.builtin.dim]: trying to load setting definitions from old format...
> 2019-04-06 18:47:07.316 T:1899455216   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)AllowShutdown75: succeeded
> 2019-04-06 18:47:07.317 T:1899455216   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated

Does this indicate that the problem is with the backend?  I do not see any messages in the backend log related to this, so I will have to restart it with debug logging enabled and check again.

**Comment by knappster1** [comment] 2019-04-07 19:49
My logs were taken yesterday.  I checked again and did not see these messages.  However, while i have block backend shutdown enabled, things appear to behave correctly.  Mythwelcome shows that it is idle when remote kodi is active.  After the kodi screensaver turns on, the backend counts down for shutdown.  Could it be that when block shutdown is disabled, the allow_shutdown is never being sent, so the backend defaults to blocking shutdown for that client?

**Comment by janbar** [comment] 2019-04-08 12:12
@knappster1 , currently if the setting "Block backend shudown" is disabled, I don't send the command "ALLOW_SHUTDOWN". I considered that the backend allowed shutdown by default. Seems it isn't the case regarding your feedback.

**Comment by janbar** [comment] 2019-04-08 15:08
I released the new version of the addon (5.10.7) which force "ALLOW_SHUTDOWN" on deactivating the gui of kodi, even if the setting "block shutdown" isn't checked.

**Comment by Miwer** [comment] 2019-04-08 23:15
Ok, so i have tested some things now, and I actually cannot produce my problem as originally reported. I just sat through an entire cartoon movie on Plex with my daughter, without mythbackend going to sleep, so it seems to be blocked alright.

So instead I think my problem might have to do with the allow_shutdown during kodi screensaver.
My backend is set to sleep after 15 minutes, and my kodi will turn off after 30 minutes screensaver, so I actually have a 15 minute window, where Kodi is on (but in screensaver) and my backend is sleeping. If I exit the screensaver during that window, Kodi will have to send a WOL signal to my backend to wake it again. Maybe that doesn't happen sometimes, I'm not sure. Testing it right now it seems to work fine, kodi sends a WOL packet, and my backend wakes up within a few seconds. I usually don't have issues with WOL when starting Kodi from scratch - the backend is always awake from sleep within a few seconds of Kodi startup.

So I always run with the block setting enabled, and that means as soon as my Kodi starts and MythPlugin connects, it sends the block_shutdown, and keeps my backend alive.
As soon as the Kodi screensaver activates, it sends allow_shutdown, and my backend will go to idle mode and sleep after 15 minutes.

    (Kodi idle screensaver = allow shutdown)
    Kodi:
    2019-04-08 23:20:23.331 T:4087423856   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: ALLOW_SHUTDOWN
    2019-04-08 23:20:23.338 T:4087423856   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)AllowShutdown75: succeeded
    2019-04-08 23:20:29.152 T:3588211568   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_COUNTDOWN 900 (2)
    2019-04-08 23:20:39.152 T:3588211568   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_COUNTDOWN 890 (2)

    Backend:
    Apr  8 23:18:44 MythServer mythbackend: mythbackend[1573]: N Scheduler scheduler.cpp:3269 (HandleIdleShutdown) Blocking shutdown because of a connected client
    (allow_shutdown)
    Apr  8 23:20:29 MythServer mythbackend: mythbackend[1573]: N Scheduler scheduler.cpp:3245 (HandleIdleShutdown) I'm idle now... shutdown will occur in 900 seconds.
    Apr  8 23:20:39 MythServer mythbackend: mythbackend[1573]: N Scheduler scheduler.cpp:3254 (HandleIdleShutdown) 890 secs left to system shutdown!

exiting Kodi screensaver, and the backend is again blocked from shutdown.

    (exit Kodi screensaver (before backend sleep))
    Kodi:
    2019-04-08 23:22:29.902 T:3588211568   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_COUNTDOWN 780 (2)
    2019-04-08 23:22:34.261 T:4087423856   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: BLOCK_SHUTDOWN
    2019-04-08 23:22:34.266 T:4087423856   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)BlockShutdown75: succeeded

    Backend:
    Apr  8 23:22:29 MythServer mythbackend: mythbackend[1573]: N Scheduler scheduler.cpp:3254 (HandleIdleShutdown) 780 secs left to system shutdown!
    (block_shutdown)
    Apr  8 23:22:38 MythServer mythbackend: mythbackend[1573]: N Scheduler scheduler.cpp:3269 (HandleIdleShutdown) Blocking shutdown because of a connected client
    Apr  8 23:22:53 MythServer mythbackend: mythbackend[1573]: N Scheduler scheduler.cpp:3269 (HandleIdleShutdown) Blocking shutdown because of a connected client

So if the allow_shutdown during Kodi screensaver is intended, it seems to work just fine. Maybe I can work around the problem by aligning the idle time of kodi and my backend, if it's a WOL issue.

**Comment by knappster1** [comment] 2019-04-11 02:26
@miwer, in 5.10.6 it appears that if you disable the block backend setting that it may actually block the shutdown until you exit kodi.  @janbar appears to have changed this in 5.10.7, which I have not had an opportunity to test yet.  However, if you want to prevent backend shutdown, couldn't you increase the kodi screensaver timer?

Alternatively you might be able to create a script that sends a lock command to the backend before launching kodi and unlocking when kodi exits.

**Comment by knappster1** [comment] 2019-04-13 12:57
@janbar, I am just waiting for the updated raspbian jessie binary to test this.  I would be happy to compile it and test it in the meantime if you can point me in the right direction.

I have a follow-up question, though.  Whether the setting is enabled or disabled, what happens if kodi restarts (or I suppose this applies even if kodi does not restart and it just stays powered on) while the backend is offline?  Will the allow_shutdown be sent when it reconnects or could we end up in a state where kodi tries to send the allow_shutdown command while the backend is offline and does not resend it when the backend comes back online and kodi reconnects?  I ask because I recently had to shutdown kodi to get my backend to shutdown again, but everything works as expected most of the time and has worked again since then.  I did not think to see what would happen if i just waited for the screensaver again instead of closing kodi...

**Comment by janbar** [comment] 2019-04-15 08:46
@knappster1 , the blocking shutdown is linked with a connection. When the connection is closed, the blocking is no longer enabled. So exiting kodi or sleeping kodi host or disconnecting network, will disable any blocking.
In the last update of the addon (5.10.7), I send allow shutdown when kodi is going to eco mode (screen saver), even if the blocking option hasn't been checked. and that just to insure the backend is allowed to shutdown. Normally the blocking isn't enable for a control connection unless you send "block_shutdown". Only a transfer connection blocks the backend shutdown by default: when you are watching a live or a recording the addon opens a transfer connection to download the stream.

**Comment by ikke-t** [comment] 2019-04-15 19:08
@janbar thanks for working on this. It affects my systems too. Where should I get the update, as you mentioned you updated version to 5.10.7? If I press update plugin in my Kodi (XBian), it says it's already latest. It is actually 5.10.6 still. Did you just tag it in github, and I should clone it, or should I be able to get new version via GUI?

**Comment by ikke-t** [comment] 2019-04-15 19:39
Exciting. Now that I enabled the logging, backend all the sudden shuts down nicely. I keep my eye on it with logs for a while. Here's what it does when it works:

```
2019-04-15 21:59:56.685 T:1911636720   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: ALLOW_SHUTDOWN
2019-04-15 22:06:34.491 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_COUNTDOWN 900 (2)
2019-04-15 22:06:44.491 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_COUNTDOWN 886 (2)
2019-04-15 22:06:54.491 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_COUNTDOWN 876 (2)

...

2019-04-15 22:21:29.637 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_COUNTDOWN 1 (2)
2019-04-15 22:21:30.637 T:1642058480   DEBUG: AddOnLog: MythTV PVR Client: RunHouseKeeping
2019-04-15 22:21:35.540 T:1694466800   DEBUG: Previous line repeats 4 times.
2019-04-15 22:21:35.541 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvMessageLength: 42
2019-04-15 22:21:35.542 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SHUTDOWN_NOW (1)
2019-04-15 22:21:36.548 T:1642058480   DEBUG: AddOnLog: MythTV PVR Client: RunHouseKeeping
2019-04-15 22:21:37.078 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvMessageLength: 71
2019-04-15 22:21:37.079 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)RcvBackendMessage: SYSTEM_EVENT MASTER_SHUTDOWN SENDER loota (4)
2019-04-15 22:21:38.085 T:1642058480   DEBUG: AddOnLog: MythTV PVR Client: RunHouseKeeping
2019-04-15 22:21:38.672 T:1694466800  NOTICE: AddOnLog: MythTV PVR Client: (CPPMyth)ReceiveData: socket(0x42d1d04) timed out (0)
2019-04-15 22:21:38.673 T:1694466800  NOTICE: AddOnLog: MythTV PVR Client: (CPPMyth)ReceiveData: socket(0x42d1d04) timed out (1)
2019-04-15 22:21:38.674 T:1694466800  NOTICE: AddOnLog: MythTV PVR Client: (CPPMyth)ReceiveData: socket(0x42d1d04) timed out (2)
2019-04-15 22:21:38.674 T:1694466800  NOTICE: AddOnLog: MythTV PVR Client: (CPPMyth)ReceiveData: socket(0x42d1d04) timed out (3)
2019-04-15 22:21:38.675 T:1694466800  NOTICE: AddOnLog: MythTV PVR Client: (CPPMyth)ReceiveData: socket(0x42d1d04) timed out (4)
2019-04-15 22:21:38.675 T:1694466800  NOTICE: AddOnLog: MythTV PVR Client: (CPPMyth)ReceiveData: socket(0x42d1d04) timed out (5)
2019-04-15 22:21:38.675 T:1694466800   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)HangException: protocol connection hang with error 110
2019-04-15 22:21:38.676 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)AnnounceStatus: (0x3718928) DISCONNECTED
2019-04-15 22:21:38.678 T:1642058480   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: DONE
2019-04-15 22:21:38.679 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)__connectAddr: connected to socket(0x42d1d04)
2019-04-15 22:21:38.680 T:1642058480   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)Close: done
2019-04-15 22:21:38.681 T:1694466800   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: MYTH_PROTO_VERSION 91 BuzzOff
2019-04-15 22:21:38.681 T:1642058480   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)SendCommand: DONE
2019-04-15 22:21:38.681 T:1642058480   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)Close: done
2019-04-15 22:21:38.682 T:1642058480   DEBUG: CAddonCallbacksAddon - QueueNotification - MythTV PVR Client - Error Message : 'Yhteys MythTv:hen katkennut'
```

**Comment by janbar** [comment] 2019-04-16 08:55
Currently I cannot test the MythTV feature because my backend is installed on my home file server and never shutdown automatically. IMO to test  the backend sleeping, you should **disable** the addon option "Block backend shutdown", and then check your backend will shutdown when you no longer watch a live show or a recording. Finally if it works as intended you can enable the addon option that will block the shutdown when you keep activated kodi. Normally the addon will send the message "allow_shutdown" when kodi is inactivated or simply the connections will be closed when kodi will sleep or stop, that must allow the backend shutdown.

**Comment by knappster1** [comment] 2019-12-19 03:47
@janbar I thought I would report that this still does not quite work as expected for me.  I have "Block Backend Shutdown" disabled.  It seems to work as expected if my backend is online when I power my kodi box on and/or enable pvr.mythtv on my kodi box.  However, if kodi is running with pvr.mythtv enabled when my backend comes back online, it does not shutdown again until kodi is powered down, rebooted, or pvr.mythtv is disabled.

My assumption is that since "allow_shutdown" was already sent from pvr.mythtv, it is not sent again when the backend turns off and back on.  My workaround has been to add a cron job that disables pvr.mythtv each night and then I will manually enable it again when I want to use it (which could be days later).

It's not a major concern for me, but as 8 months have passed and this issue is still open, I thought it worth reporting.  The addon works quite well for me otherwise.

**Comment by janbar** [comment] 2019-12-19 14:39
Okay. So I have to recall the backend for allow_shutdown every time we reconnect.

**Comment by knappster1** [comment] 2019-12-21 12:51
@janbar based on the behavior I'm experiencing I *think* that is correct.  I don't believe that the mythbackend logs really have any useful information as to why it's behaving this way.  My usage may be a unique case since others do not seem to be reporting the same thing.  I don't expect you to invest a lot of time trying to fix this, particularly if there are any risks of breaking any other functionality.  However, if you push out an update to resolve it, I will happily test it when it becomes available on libreelec.

**Comment by ikke-t** [comment] 2019-12-22 03:20
You are not alone. I just had a couple weeks of backend constantly on for sone reason. I only use mythtv plugin from Kodi as frontend. It worked for long though, but Now I use another Kodi occasionally, and shut it down often. So my behavior changed, which could bring the problem back. I can report back after holidays.

**Comment by janbar** [comment] 2020-01-06 08:01
I have to add the call here: https://github.com/janbar/pvr.mythtv/blob/284204396d42152941a2c22c6a914c74ec779709/src/pvrclient-mythtv.cpp#L307

**Comment by janbar** [comment] 2020-01-06 22:58
That's weird... If the addon setting 'blockShutdown' is set to false then never the command block_shutdown will be sended to the backend and it should be allowed to shut because this is the default behavior for the backend.

**Comment by janbar** [comment] 2020-01-08 08:11
All about is explained here: https://www.mythtv.org/wiki/Idle_Screen

The addon setting blockShutdown has no more effect since the addon connect as frontend (block shutdown is true by default).
The addon allows shutdown on idle screen. So you have to setup the idle screen on kodi to allow shutdown.

**Comment by janbar** [comment] 2020-01-08 11:37
I will change the behavior of the setting blockshutdown, when false The addon will send allow_shutdown on connect and the backend will shutdown even the addon is active or kodi not idle (but not watching).

**Comment by janbar** [comment] 2020-01-08 23:42
After review the current code is right. The behavior is the same as MythFrontend. i.e the allow shutdown is effective only on idle screen. Under the hood we need an event to wake up the backend. This event is the gui becomes active. This is the reason why MythFrontend works like that and I made the same.
Finally the setting blockShutdown has no usage since the addon connect as a frontend because it is always true until the gui becomes idle (on idle the addon send allow shutdown).
to fix the issue you have to configure the idle state in kodi in the same way you configure it in MythFrontend to enable the allow shutdown.

**Comment by janbar** [comment] 2020-01-09 13:29
One thing I missed is to allow shutdown again after the backend restart and kodi still in power saving mode. To fix that, I will change the setting 'blockShutdown' to the new one 'allowShutdown' (default = true, so you have nothing to change in the settings), and I will call again allow shutdown on reconnect if Kodi still in power saving mode. I think it will fix all the bugs declared in this issue.

**Comment by janbar** [comment] 2020-01-09 19:08
That is fixed now with the new releases:
- Leia : 5.10.15
- Matrix : 6.2.6

The setting block_shutdown is replaced by allow_shutdown and the value is TRUE by default.

**Allow shutdown is send to the backend on idle state. The idle state is activated when the "screensaver" is activated. So you have to setup the screensaver in the Kodi setting, i.e enabling the black screen.**

I updated the help in the Kodi wiki: [MythTV_PVR](https://kodi.wiki/view/MythTV_PVR#Advanced)

**Closed as completed by janbar** 2020-01-09 19:08 UTC

**Comment by knappster1** [comment] 2020-01-11 13:17
Thanks @janbar !  I will update it as soon as it becomes available on LibreELEC 😄

**Comment by knappster1** [comment] 2020-01-26 15:56
LibreELEC has not updated yet, but my raspbian box with pipplware repo updated and it is now working as expected for me.  Thanks again!

Kodi 18.5
pvr.mythtv 5.10.15

**Comment by janbar** [comment] 2020-01-26 19:30
Nice to heard :-)
